// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260809120730_addedMJCPRojectSeed")]
    partial class addedMJCPRojectSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Project", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("isDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("project_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("remarks")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            id = new Guid("11111111-1111-1111-1111-111111111111"),
                            isDeleted = false,
                            project_name = "SBF Project",
                            remarks = ""
                        },
                        new
                        {
                            id = new Guid("22222222-2222-2222-2222-222222222222"),
                            isDeleted = false,
                            project_name = "Yilujia Accounting Project",
                            remarks = ""
                        },
                        new
                        {
                            id = new Guid("33333333-3333-3333-3333-333333333333"),
                            isDeleted = false,
                            project_name = "MUANA HRIS Project",
                            remarks = ""
                        },
                        new
                        {
                            id = new Guid("44444444-4444-4444-4444-444444444444"),
                            isDeleted = false,
                            project_name = "Suntech Accounting Project",
                            remarks = ""
                        },
                        new
                        {
                            id = new Guid("55555555-5555-5555-5555-555555555555"),
                            isDeleted = false,
                            project_name = "Concord ERP Project",
                            remarks = ""
                        },
                        new
                        {
                            id = new Guid("66666666-6666-6666-6666-666666666666"),
                            isDeleted = false,
                            project_name = "MJC Accounting Project",
                            remarks = ""
                        });
                });

            modelBuilder.Entity("backend.Models.Ticket", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("contact_email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("contact_person")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("project_id")
                        .HasColumnType("char(36)");

                    b.Property<string>("reference_no")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("project_id");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("backend.Models.Ticket", b =>
                {
                    b.HasOne("backend.Models.Project", "Project")
                        .WithMany("Tickets")
                        .HasForeignKey("project_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Project");
                });

            modelBuilder.Entity("backend.Models.Project", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
